/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddMedication.java
 *
 * Created on May 5, 2015, 1:37:37 PM
 */
package gym;

import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
/**
 *
 * @author ManoJ
 */
public class AddMedication extends javax.swing.JInternalFrame {

    /** Creates new form AddMedication */
    public AddMedication() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        today = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMedId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tMedQty = new javax.swing.JTextField();
        tMedPrc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tMedName = new javax.swing.JTextField();
        txtSupId = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tSupName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        tPrc = new javax.swing.JTextField();
        tQty = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Add Medication");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        today.setText("Date: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Add Medication");

        txtMedId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedIdActionPerformed(evt);
            }
        });

        jLabel8.setText("Medication ID :");

        jLabel9.setText("Med Qty :");

        tMedPrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMedPrcActionPerformed(evt);
            }
        });

        jLabel7.setText("Med Price :");

        jLabel6.setText("Med Name :");

        tMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMedNameActionPerformed(evt);
            }
        });

        txtSupId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupIdActionPerformed(evt);
            }
        });

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Supplier ID :");

        jLabel11.setText("Supplier Name :");

        tSupName.setEditable(false);
        tSupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSupNameActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantity  :");

        jLabel13.setText("New Price  :");

        tPrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrcActionPerformed(evt);
            }
        });

        tQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tQtyActionPerformed(evt);
            }
        });

        jButton4.setText("Add New Medication ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSupId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch1))
                            .addComponent(txtMedId, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tMedQty)
                                    .addComponent(tMedName)
                                    .addComponent(tMedPrc, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tSupName, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jButton4)))))))
                .addGap(25, 25, 25))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(84, 84, 84)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tQty, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tPrc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(today)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMedPrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMedQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tPrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
  Connection con;
Statement st;
String i;
String a,b,c,d,e;
String a1,a2,a3,a4;
	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception exc){JOptionPane.showMessageDialog(null,exc);}
	}
    	void search(String z,String p)
	{	set();
        

        
            try
		{
		ResultSet rs=st.executeQuery("select * from  medicationT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d = rs.getString(5);
                         e = rs.getString(6);
                         
                       // System.out.println(i);System.out.println(a);System.out.println(b);System.out.println(c);
                       // System.out.println(d);System.out.println(e);
                        
                       // System.out.println(z);System.out.println(p);
                        
                       if( (i.equals(z))&&(e.equals(p)) ){
                        tMedName.setText(a);
                        tMedQty.setText(b);               
                        tMedPrc.setText(c);                                                                                                            
                      }                               
                }
		}catch(Exception ex){}
            
            
                //to get supplier Name
            try
		{
		ResultSet rs=st.executeQuery("select * from  SupplierT");
		while(rs.next())
		{   
			a1=rs.getString(1);
			a2=rs.getString(2);
                        a3= rs.getString(3);
                        a4= rs.getString(4);
                       // System.out.println(a1);System.out.println(a2);System.out.println(a3);System.out.println(a4);
                        
                        
                       if( a1.equals(p)){
                        tSupName.setText(a2);                                                                   
                      }                               
                }
		}catch(Exception ex){}


            
	}



  
    
    
    
    
    
    
    
    
    
    
    
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
   SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       Date date = new Date();
       today.setText("Date: "+dateFormat.format(date));// TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameActivated

private void txtMedIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedIdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtMedIdActionPerformed

private void tMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMedNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tMedNameActionPerformed

private void txtSupIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupIdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtSupIdActionPerformed

private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
 String medId = txtMedId.getText();
 String supId = txtSupId.getText();
    search(medId,supId); 
    
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnSearch1ActionPerformed

private void tSupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSupNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tSupNameActionPerformed

private void tMedPrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMedPrcActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tMedPrcActionPerformed

private void tPrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrcActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPrcActionPerformed

private void tQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tQtyActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tQtyActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


                if (txtMedId.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Med ID Not Entered.");
                return;
                }  
                
                if (txtSupId.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Med ID Not Entered.");
                return;
                }
                
                
                
                String qty = tQty.getText();
                String prc = tPrc.getText();  
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                //set today date to string variable
                   Date date = new Date();
                  String mDate=dateFormat.format(date);
    
                if(prc.equals("")){
                prc=c;
                }
                
                 //adding old qty with old qty
                //but first we need to convert them to integer.. then to Strings
                
                   Integer aa = Integer.valueOf(qty);         
                   Integer bb = Integer.valueOf(tMedQty.getText());
                        //if new Qty is not in this, bb=0;
                        if(tMedQty.getText().equals("")){
                               bb=0;
                        }
                   System.out.println("new Qty  "+aa);
                   aa=aa+bb;     
                   qty = Integer.toString(aa);
                   /*System.out.println("Old qty  "+bb);
                   System.out.println("string qty=  " + qty);
                  System.out.println("qty  "+qty);
                  System.out.println("prc  "+prc);
                  System.out.println("date  "+mDate);*/
                  
             try{       PreparedStatement pstmt = null;
               String sql = "UPDATE MedicationT SET medQty=?,medPrice=?,supDate=?,medId=?,medName=?,supId=? WHERE medId = ? AND supId=?";
               pstmt = con.prepareStatement(sql);
        
                  
                  pstmt.setString(1,qty ); 
                  pstmt.setString(2, prc); 
                  pstmt.setString(3,mDate); 
                  pstmt.setString(4,txtMedId.getText() ); 
                  pstmt.setString(5, tMedName.getText()); 
                  pstmt.setString(6,txtSupId.getText()); 
                  
                  pstmt.setString(7,txtMedId.getText() ); 
                  pstmt.setString(8,txtSupId.getText() ); 
                  pstmt.executeUpdate(); 
                   
                  
                  System.out.println("med id  "+txtMedId.getText());
                  System.out.println("med name  "+tMedName.getText());
                  System.out.println("sup Id  "+txtSupId.getText());
              
        
     JOptionPane.showMessageDialog(null,"Medication Updated..!");
                con.close();
		}catch(Exception x){
                JOptionPane.showMessageDialog(null,x);}
                  
    
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

     if (txtMedId.getText().equals("")){
                JOptionPane.showMessageDialog(null,"MedID Not Entered.");
                return;
                }    
    if (txtSupId.getText().equals("")){
                JOptionPane.showMessageDialog(null,"SupID Not Entered.");
                return;
                }  
    if (tMedName.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Med Name Not Entered.");
                return;
                } 
    if (tMedPrc.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Med Price Not Entered.");
                return;
                }
    if (tMedQty.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Med Quantity Not Entered.");
                return;
                }
    
    
     SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                //set today date to string variable
                   Date date = new Date();
                  String mDate=dateFormat.format(date);
    try{ 
        PreparedStatement pstmt = null;
        String query = "insert into MedicationT(medId,medName,medQty,medPrice,supDate,supId) values(?,?, ?, ?, ?, ?)";

     pstmt = con.prepareStatement(query); 
      pstmt.setString(1, txtMedId.getText()); 
      pstmt.setString(2,tMedName.getText() ); 
      pstmt.setString(3, tMedQty.getText()); 
      pstmt.setString(4,tMedPrc.getText()); 
      pstmt.setString(5,mDate ); 
      pstmt.setString(6,txtSupId.getText()); 

      pstmt.executeUpdate(); 
     JOptionPane.showMessageDialog(null,"New Medication Added..!");
                con.close();
		}catch(Exception qqwe){
                JOptionPane.showMessageDialog(null,qqwe);}
    
    
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tMedName;
    private javax.swing.JTextField tMedPrc;
    private javax.swing.JTextField tMedQty;
    private javax.swing.JTextField tPrc;
    private javax.swing.JTextField tQty;
    private javax.swing.JTextField tSupName;
    private javax.swing.JLabel today;
    private javax.swing.JTextField txtMedId;
    private javax.swing.JTextField txtSupId;
    // End of variables declaration//GEN-END:variables
}
