/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckOtherPayments.java
 *
 * Created on May 6, 2015, 11:58:09 PM
 */
package gym;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
/**
 *
 * @author ManoJ
 */
public class CheckOtherPayments extends javax.swing.JInternalFrame {

    /** Creates new form CheckOtherPayments */
    public CheckOtherPayments() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tp = new javax.swing.JTextPane();

        setClosable(true);
        setTitle("Check Other Payments");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tp.setEditable(false);
        jScrollPane1.setViewportView(tp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Connection con;
Statement st;
String i,a,b,c,d,e,f,g,i1,a1,b1,c1,d1,e1,f1,g1;

	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception e){JOptionPane.showMessageDialog(null,e);}
	}
        	
        void search()
                
	{	tp.setText(tp.getText()+"\n"+"Member No"+"\t\t"+"Member Name"+"\t"+"For");
                tp.setText(tp.getText()+"\n------------------------------------------------------------------------------------------------------");
                set();


            try
		{
		ResultSet rs=st.executeQuery("select * from  ProvideTrtmntT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d= rs.getString(5);
                        System.out.println("B"+b);
                        if (!b.equals(null))
                        {
//                                         try
//                                        {
//                                        ResultSet rs1=st.executeQuery("select * from  MemberT");
//                                        while(rs.next())
//                                        {
//                                                i1=rs1.getString(1);
//                                                a1=rs1.getString(2);
//                                                b1= rs1.getString(3);
//                                                c1= rs1.getString(4);
//                                                d1 =rs1.getString(5);
//                                                e1=rs1.getString(6);
//                                                f1=rs1.getString(7);
//                                                g1=rs1.getString(8);
//                                                
//                                                if(i1.equals(i)){
//                                              
//                                                     tp.setText(tp.getText()+"\n"+i+"\t\t"+a1+"\t\t"+"Treatment");
//                                                }
//
//                                        }
//                                        }catch(Exception e){JOptionPane.showMessageDialog(null,"Reading1:"+e);}
                            
                            
                            }
                        
                        

		}
		}catch(Exception e){JOptionPane.showMessageDialog(null,"Reading:"+e);}
            

	}
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    search();
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane tp;
    // End of variables declaration//GEN-END:variables
}
