/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * checkPayments.java
 *
 * Created on May 6, 2015, 9:35:31 PM
 */
package gym;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;

/**
 *
 * @author ManoJ
 */
public class checkPayments extends javax.swing.JInternalFrame {

    /** Creates new form checkPayments */
    public checkPayments() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tp = new javax.swing.JTextPane();

        setClosable(true);
        setTitle("Check Member Payments");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tp.setEditable(false);
        jScrollPane1.setViewportView(tp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
// TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameClosed

    




    Connection con;
Statement st;
String i,a,b,c,d,e,f,g;

	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception e){JOptionPane.showMessageDialog(null,e);}
	}
        	
        void search()
                
	{	tp.setText(tp.getText()+"\n"+"Member No"+"\t\t"+"Member Name"+"\t"+"Last Renew Date");
                tp.setText(tp.getText()+"\n------------------------------------------------------------------------------------------------------");
                set();
                  SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                   Date date = new Date();
                  String reg=dateFormat.format(date);
                  
                  String yr,mn,dt;
                    int iyr,imn,idt;
                    String syr,smn,sdt;
                    int  isyr,ismn,isdt;
                    syr=reg.substring(0,4);
                    smn=reg.substring(5,7);
                    sdt=reg.substring(8,10);
                        isyr= Integer.valueOf(syr); 
                        ismn= Integer.valueOf(smn); 
                         isdt= Integer.valueOf(sdt);
                         
                        
                         if(ismn==1){ismn=10;}
                         if(ismn==2){ismn=11;}
                         if(ismn==3){ismn=12;}
                         if(ismn==4){ismn=1;}
                         if(ismn==5){ismn=2;}
                         if(ismn==6){ismn=3;}
                         if(ismn==7){ismn=4;}
                         if(ismn==8){ismn=5;}
                         if(ismn==9){ismn=6;}
                         if(ismn==10){ismn=7;}
                         if(ismn==11){ismn=8;}
                         if(ismn==12){ismn=9;}
                         
                         
                         
                   System.out.println("SystemDate: "+isyr+"  "+ismn+"  "+isdt);
            try
		{
		ResultSet rs=st.executeQuery("select * from  MemberT");
		while(rs.next())
		{
			i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d = rs.getString(5);
                        e=rs.getString(6);
                        f=rs.getString(7);
                        g=rs.getString(8);
                               yr=g.substring(0,4);
                                mn=g.substring(5,7);
                                dt=g.substring(8,10);
                        iyr= Integer.valueOf(yr); 
                        imn= Integer.valueOf(mn); 
                         idt= Integer.valueOf(dt);                          
                        //System.out.println("RegDate: "+iyr+"  "+imn+"  "+idt);
                  
                      if(iyr<isyr){
                       tp.setText(tp.getText()+"\n"+i+"\t\t"+a+"\t\t"+g);    
                    }
                    else if(imn<ismn){
                    tp.setText(tp.getText()+"\n"+i+"\t\t"+a+"\t\t"+g);  
                    }
                    else if(idt<isdt){
                    tp.setText(tp.getText()+"\n"+i+"\t\t"+a+"\t\t"+g);  
                    }

		}
		}catch(Exception e){JOptionPane.showMessageDialog(null,"Reading:"+e);}
            

	}
    
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
search();    // TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane tp;
    // End of variables declaration//GEN-END:variables
}
