/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Mar 27, 2015, 5:12:26 PM
 */
package gym;

import java.awt.Dimension;



/**
 *
 * @author ManoJ
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        InsMenu = new javax.swing.JMenu();
        MemberMenu = new javax.swing.JMenuItem();
        instMenu = new javax.swing.JMenuItem();
        menuPhy = new javax.swing.JMenuItem();
        itSup = new javax.swing.JMenuItem();
        AddPhysioth = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        UpdateMenu = new javax.swing.JMenu();
        UpMemberMenu = new javax.swing.JMenuItem();
        upIns = new javax.swing.JMenuItem();
        upPhy = new javax.swing.JMenuItem();
        uSupplier = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        iInsToMem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness Center Customer Registration System");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(-4144960,true));
        desktop.setForeground(new java.awt.Color(-1,true));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\ManO\\My\\MyJava\\J sftwr\\a.jpg")); // NOI18N
        jLabel1.setBounds(0, 0, 1000, 600);
        desktop.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        InsMenu.setBackground(new java.awt.Color(-16777216,true));
        InsMenu.setText("Add");
        InsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsMenuActionPerformed(evt);
            }
        });

        MemberMenu.setText("Member");
        MemberMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberMenuActionPerformed(evt);
            }
        });
        InsMenu.add(MemberMenu);

        instMenu.setText("Instructor");
        instMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instMenuActionPerformed(evt);
            }
        });
        InsMenu.add(instMenu);

        menuPhy.setText("Physican");
        menuPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhyActionPerformed(evt);
            }
        });
        InsMenu.add(menuPhy);

        itSup.setText("Supplier");
        itSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSupActionPerformed(evt);
            }
        });
        InsMenu.add(itSup);

        AddPhysioth.setText("Physiotherapist");
        AddPhysioth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPhysiothActionPerformed(evt);
            }
        });
        InsMenu.add(AddPhysioth);

        jMenuItem2.setText("Medication");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        InsMenu.add(jMenuItem2);

        jMenuBar1.add(InsMenu);

        UpdateMenu.setText("Update");
        UpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMenuActionPerformed(evt);
            }
        });

        UpMemberMenu.setText("Update Member");
        UpMemberMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpMemberMenuMouseClicked(evt);
            }
        });
        UpMemberMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpMemberMenuActionPerformed(evt);
            }
        });
        UpdateMenu.add(UpMemberMenu);

        upIns.setText("Update Instructor");
        upIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upInsActionPerformed(evt);
            }
        });
        UpdateMenu.add(upIns);

        upPhy.setText("Update Physican");
        upPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upPhyActionPerformed(evt);
            }
        });
        UpdateMenu.add(upPhy);

        uSupplier.setText("Update Supplier");
        uSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uSupplierActionPerformed(evt);
            }
        });
        UpdateMenu.add(uSupplier);

        jMenuItem1.setText("Update Physiotherapist");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        UpdateMenu.add(jMenuItem1);

        jMenuBar1.add(UpdateMenu);

        menuTools.setText("Tools");

        iInsToMem.setText("Assign Instructor To Member");
        iInsToMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iInsToMemActionPerformed(evt);
            }
        });
        menuTools.add(iInsToMem);

        jMenuItem4.setText("Treatment");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem4);

        jMenuItem5.setText("Prescribe Medication");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem5);

        jMenuItem9.setText("Check Member Payments");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem9);

        jMenuBar1.add(menuTools);

        jMenu1.setText("Payments");

        jMenuItem3.setText("Member Registation");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("Member Renew");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Treatment");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Prescribe");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

private void UpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMenuActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_UpdateMenuActionPerformed


String a;
private void UpMemberMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpMemberMenuActionPerformed
// TODO add your handling code here:
    
    UpdateMember mm=new UpdateMember();
    desktop.add(mm);
    mm.setVisible(true);
}//GEN-LAST:event_UpMemberMenuActionPerformed

private void UpMemberMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpMemberMenuMouseClicked
// TODO add your handling code here:
    
}//GEN-LAST:event_UpMemberMenuMouseClicked

private void upInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upInsActionPerformed
UpIns v=new UpIns();
    desktop.add(v);
    v.setVisible(true);    
    // TODO add your handling code here:
}//GEN-LAST:event_upInsActionPerformed

private void iInsToMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iInsToMemActionPerformed

    InsToMem v=new InsToMem();
    desktop.add(v);
    v.setVisible(true);
    
    // TODO add your handling code here:
}//GEN-LAST:event_iInsToMemActionPerformed

private void upPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upPhyActionPerformed
UpdatePhysican v=new UpdatePhysican();
    desktop.add(v);
    v.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_upPhyActionPerformed

private void uSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uSupplierActionPerformed
UpSupplier v=new UpSupplier();
    desktop.add(v);
    v.setVisible(true);
    
    // TODO add your handling code here:
}//GEN-LAST:event_uSupplierActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
UpPhysiotherapist v= new UpPhysiotherapist();
   desktop.add(v);
    v.setVisible(true);
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    //this will open the frame in max 
  // setExtendedState(NewJFrame.MAXIMIZED_BOTH); // TODO add your handling code here:
    setSize(new Dimension(1000, 600));
   //  setExtendedState(NewJFrame.MAXIMIZED_BOTH); 
}//GEN-LAST:event_formWindowOpened

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
Treatment v= new Treatment();
   desktop.add(v);
    v.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
PrescribeMedication v= new PrescribeMedication();
   desktop.add(v);
    v.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void InsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsMenuActionPerformed
// TODO add your handling code here:

 
}//GEN-LAST:event_InsMenuActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
    AddMedication v= new AddMedication();
   desktop.add(v);
    v.setVisible(true);
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void AddPhysiothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPhysiothActionPerformed
AddPhysiotherapist v= new AddPhysiotherapist();
   desktop.add(v);
    v.setVisible(true);
    
    // TODO add your handling code here:
}//GEN-LAST:event_AddPhysiothActionPerformed

private void itSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSupActionPerformed
AddSupplier v=new AddSupplier();
    desktop.add(v);
    v.setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_itSupActionPerformed

private void menuPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhyActionPerformed

      AddPhysican v=new AddPhysican();
    desktop.add(v);
    v.setVisible(true);
    
    // TODO add your handling code here:
}//GEN-LAST:event_menuPhyActionPerformed

private void instMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instMenuActionPerformed
// TODO add your handling code here:
     AddInstructor v=new AddInstructor();
desktop.add(v);
    v.setVisible(true);
}//GEN-LAST:event_instMenuActionPerformed

private void MemberMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberMenuActionPerformed
// TODO add your handling code here:
       AddMemberFrame mm=new AddMemberFrame();
    desktop.add(mm);
    mm.setVisible(true);
    
}//GEN-LAST:event_MemberMenuActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
AddPayment v =new AddPayment();// TODO add your handling code here:
   desktop.add(v);
   v.setVisible(true);
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
MemberRenew  v =new   MemberRenew();// TODO add your handling code here
  desktop.add(v);
   v.setVisible(true);
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
TreatmentPayment v =new TreatmentPayment();// TODO add your handling code here:
desktop.add(v);
   v.setVisible(true);
}//GEN-LAST:event_jMenuItem7ActionPerformed

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
PrescribePayment v =new PrescribePayment();// TODO add your handling code here:
desktop.add(v);
   v.setVisible(true);
}//GEN-LAST:event_jMenuItem8ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    checkPayments v =new checkPayments();
    desktop.add(v);
   v.setVisible(true);        
            // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddPhysioth;
    private javax.swing.JMenu InsMenu;
    private javax.swing.JMenuItem MemberMenu;
    private javax.swing.JMenuItem UpMemberMenu;
    private javax.swing.JMenu UpdateMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem iInsToMem;
    private javax.swing.JMenuItem instMenu;
    private javax.swing.JMenuItem itSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuPhy;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenuItem uSupplier;
    private javax.swing.JMenuItem upIns;
    private javax.swing.JMenuItem upPhy;
    // End of variables declaration//GEN-END:variables
}
