/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrescribeMedication.java
 *
 * Created on May 5, 2015, 10:42:51 PM
 */
package gym;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author ManoJ
 */
public class PrescribeMedication extends javax.swing.JInternalFrame {

    /** Creates new form PrescribeMedication */
    public PrescribeMedication() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paySch = new javax.swing.JButton();
        payType = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tPAmt2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnClr = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        tPayNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        memSch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tPAmt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        phyName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tPAmt1 = new javax.swing.JTextField();
        memName = new javax.swing.JTextField();
        phySch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Prescribe Medicine");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        paySch.setText("Search");
        paySch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paySchActionPerformed(evt);
            }
        });

        payType.setEditable(false);
        payType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payTypeActionPerformed(evt);
            }
        });

        jLabel12.setText("Medicine Name :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Prescribe Medicine");

        tPAmt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPAmt2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Medicine ID :");

        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tPayNo.setEditable(false);
        tPayNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPayNoActionPerformed(evt);
            }
        });

        jLabel10.setText("Member No :");

        memSch.setText("Search");
        memSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memSchActionPerformed(evt);
            }
        });

        tPAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPAmtActionPerformed(evt);
            }
        });

        phyName.setEditable(false);
        phyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phyNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Prescribe No :");

        jLabel13.setText("Member Name :");

        jLabel11.setText("Physiotherapist Name :");

        tPAmt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPAmt1ActionPerformed(evt);
            }
        });

        memName.setEditable(false);
        memName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memNameActionPerformed(evt);
            }
        });

        phySch.setText("Search");
        phySch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phySchActionPerformed(evt);
            }
        });

        jLabel8.setText("Physiotherapist ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(tPayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(67, 67, 67)
                        .addComponent(btnClr)
                        .addGap(61, 61, 61)
                        .addComponent(btnExit)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phyName, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)
                                .addComponent(tPAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phySch, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tPAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paySch, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                    .addComponent(payType, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tPAmt2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(memSch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(memName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(tPayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phySch)
                    .addComponent(tPAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paySch)
                    .addComponent(jLabel9)
                    .addComponent(tPAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(payType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memSch)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnClr)
                    .addComponent(btnAdd))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 Connection con;
Statement st;
String i;
String a,b,c,d,e;
String a1,a2,a3,a4;
	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception exc){JOptionPane.showMessageDialog(null,exc);}
	}
    	void search()
	{	set();

            try
		{
		ResultSet rs=st.executeQuery("select * from  PrescribeT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                                        
                }
		}catch(Exception hjhk){JOptionPane.showMessageDialog(null,hjhk);}
            
            Integer x = Integer.valueOf(i);         
            x=x+1;
            i = Integer.toString(x);
            tPayNo.setText(i); 
	}
               
    
    
    
    
private void paySchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paySchActionPerformed
search2(tPAmt.getText());// TODO add your handling code here:
}//GEN-LAST:event_paySchActionPerformed

private void payTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payTypeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_payTypeActionPerformed

private void tPAmt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPAmt2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPAmt2ActionPerformed

private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
tPAmt.setText("");
tPAmt2.setText("");
tPAmt1.setText("");

    // TODO add your handling code here:
}//GEN-LAST:event_btnClrActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
               
                if (tPAmt.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Physiotherapist Not Entered.");
                return;
                }
                           if (tPAmt1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Medicine ID Not Entered.");
                return;
                }
                           if (tPAmt2.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Member No Not Entered.");
                return;
                }

    try{       
               PreparedStatement pstmt = null;
                String query = "insert into PrescribeT(presNo,memberId,physId,medicId) values(?,?,?,?)";

     pstmt = con.prepareStatement(query); 
      pstmt.setString(1, i); 
      pstmt.setString(2,tPAmt2.getText() ); 
      pstmt.setString(3, tPAmt.getText()); 
      pstmt.setString(4,tPAmt1.getText()); 

      pstmt.executeUpdate(); 
     
     JOptionPane.showMessageDialog(null,"Done..!");
                con.close();
		}catch(Exception e3){
                JOptionPane.showMessageDialog(null,e3);}
}//GEN-LAST:event_btnAddActionPerformed
   



void search1(String z)
                {String b1,b2,b3;	
                    set();
             try
		{
		ResultSet rs=st.executeQuery("select * from  PhysiotherapistT");
		while(rs.next())
		{   
			b1=rs.getString(1);
			b2=rs.getString(2);
                        b3= rs.getString(3);
                        
                       if( b1.equals(z)){
                        phyName.setText(b2);                                                                        
                      }                               
                }
		}catch(Exception ex){}
	}
    
      void search2(String z)
                {String b1,b2,b3,b4,b5,b6;	
                    set();
             try
		{
		ResultSet rs=st.executeQuery("select * from  MedicationT");
		while(rs.next())
		{   
			b1=rs.getString(1);
			b2=rs.getString(2);
                        b3= rs.getString(3);
                        b4=rs.getString(4);
                        b5= rs.getString(5);
                        b6= rs.getString(6);
                        if( b1.equals(z)){
                        payType.setText(b2);                                                                        
                      }                               
                }
		}catch(Exception ex){}
	}
   
   
   
   void search3(String z)
                {String b1,b2,b3,b4,b5,b6,b7,b8;	
                    set();
             try
		{
		ResultSet rs=st.executeQuery("select * from  MemberT");
		while(rs.next())
		{   
			b1=rs.getString(1);
			b2=rs.getString(2);
                        b3= rs.getString(3);
                        b4=rs.getString(4);
                        b5= rs.getString(5);
                        b6= rs.getString(6);
                        b7=rs.getString(7);
                        b8= rs.getString(8);
                        
                        if( b1.equals(z)){
                        memName.setText(b2);                                                                        
                      }                               
                }
		}catch(Exception ex){}
	}
private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
   this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnExitActionPerformed

private void tPayNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPayNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPayNoActionPerformed

private void memSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memSchActionPerformed
search3(tPAmt2.getText());// TODO add your handling code here:
}//GEN-LAST:event_memSchActionPerformed

private void tPAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPAmtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPAmtActionPerformed

private void phyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phyNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_phyNameActionPerformed

private void tPAmt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPAmt1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPAmt1ActionPerformed

private void memNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_memNameActionPerformed

private void phySchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phySchActionPerformed
search1(tPAmt.getText());        
 
    
    // TODO add your handling code here:
}//GEN-LAST:event_phySchActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
search();
    // TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField memName;
    private javax.swing.JButton memSch;
    private javax.swing.JButton paySch;
    private javax.swing.JTextField payType;
    private javax.swing.JTextField phyName;
    private javax.swing.JButton phySch;
    private javax.swing.JTextField tPAmt;
    private javax.swing.JTextField tPAmt1;
    private javax.swing.JTextField tPAmt2;
    private javax.swing.JTextField tPayNo;
    // End of variables declaration//GEN-END:variables
}
