/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TreatmentPayment.java
 *
 * Created on May 6, 2015, 6:29:52 PM
 */
package gym;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author ManoJ
 */
public class TreatmentPayment extends javax.swing.JInternalFrame {

    /** Creates new form TreatmentPayment */
    public TreatmentPayment() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        tPayNo = new javax.swing.JTextField();
        btnClr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tTNo = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        tPAmt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        tMemName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tMemId1 = new javax.swing.JTextField();
        btnSearchT = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tTFor = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Treatment Payment");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tPayNo.setEditable(false);
        tPayNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPayNoActionPerformed(evt);
            }
        });

        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });

        jLabel1.setText("Payment No :");

        tTNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTNoActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel8.setText("Payment Amount :");

        today.setText("Date: ");

        tPAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPAmtActionPerformed(evt);
            }
        });

        jLabel10.setText("Member ID :");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tMemName.setEditable(false);
        tMemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMemNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Treatment Payment");

        jLabel11.setText("Member Name :");

        jLabel12.setText("Treatment No :");

        tMemId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMemId1ActionPerformed(evt);
            }
        });

        btnSearchT.setText("Search");
        btnSearchT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTActionPerformed(evt);
            }
        });

        jLabel13.setText("Treatement For :");

        tTFor.setEditable(false);
        tTFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addGap(19, 19, 19)
                .addComponent(tTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSearchT))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addComponent(tTFor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(tMemId1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSearch))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(tMemName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(tPAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnAdd)
                .addGap(60, 60, 60)
                .addComponent(btnClr)
                .addGap(61, 61, 61)
                .addComponent(btnExit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(today))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tPayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tTNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchT))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(tTFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tMemId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(tMemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(tPAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnClr)
                    .addComponent(btnExit))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 
 Connection con;
Statement st;
String i;
String a,b,c,d,e,f,g;
	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception exc){JOptionPane.showMessageDialog(null,exc);}
	}
    	void search()
	{	set();

            try
		{
		ResultSet rs=st.executeQuery("select * from  PaymentT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d= rs.getString(5);
                                        
                }
		}catch(Exception hjhk){JOptionPane.showMessageDialog(null,hjhk);}
            
            Integer x = Integer.valueOf(i);         
            x=x+1;
            i = Integer.toString(x);
            tPayNo.setText(i); 
	}   
    
   	void searchTrtm()
	{	set();

            try
		{
		ResultSet rs=st.executeQuery("select * from  ProvideTrtmntT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d= rs.getString(5);
                        
                        if(i.equals(tTNo.getText())){
                        tTFor.setText(d);
                        }
                        
                        
                        
                }
		}catch(Exception hjhk){JOptionPane.showMessageDialog(null,hjhk);}

	}   
     
        
        
        
    //this is for update the pNo on provide treatment table
        void a(){
            try{       PreparedStatement pstmt = null;
               String sql = "UPDATE ProvideTrtmntT SET payNo=? WHERE trtNo = ?";
               pstmt = con.prepareStatement(sql);
        
                  
                  pstmt.setString(1,tPayNo.getText() ); 
                  pstmt.setString(2,tTNo.getText()); 
                  pstmt.executeUpdate(); 

               
        
     
                con.close();
		}catch(Exception x){
                JOptionPane.showMessageDialog(null,x);}
        
        
        }
        
       	void searchMem(String z)
	{	set();
            try
		{
		ResultSet rs=st.executeQuery("select * from  MemberT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d = rs.getString(5);
                        e= rs.getString(6);
                        f= rs.getString(7);
                        g = rs.getString(8);
                        
                       if( i.equals(z)){
                        tMemName.setText(a);                                                                                 
                      }                               
                }
		}catch(Exception ex){}
            
	}
    
    
private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
               
                if (tPAmt.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Payment Amount Not Entered.");
                return;
                }
                if (tTNo.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Member ID Not Entered.");
                return;
                }           
                if (tTNo.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Treatment No Not Entered.");
                return;
                }               
                   
                String a1 = tPayNo.getText();
                String a2 = tPAmt.getText();               
                String a3 = tTNo.getText();
                //date to string
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                //set today date to string variable
                   Date date = new Date();
                  String stDate=dateFormat.format(date);
                     
    try{       
               PreparedStatement pstmt = null;
                String query = "insert into PaymentT(pNo,pAmt,pDate,pType,mmbrNo) values(?,?,?,?,?)";

     pstmt = con.prepareStatement(query); 
      pstmt.setString(1, a1); 
      pstmt.setString(2,a2 ); 
      pstmt.setString(3, stDate); 
      pstmt.setString(4, "Treatment"); 
      pstmt.setString(5,tTNo.getText() ); 
 
      pstmt.executeUpdate(); 
     
     JOptionPane.showMessageDialog(null,"Treatment Payment Added..!");
     
                a();
                con.close();
		}catch(Exception e3){
                JOptionPane.showMessageDialog(null,e3);}
    
}//GEN-LAST:event_btnAddActionPerformed

private void tPayNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPayNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPayNoActionPerformed

private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
tPAmt.setText("");
tTNo.setText(""); 
tMemName.setText("");

    // TODO add your handling code here:
}//GEN-LAST:event_btnClrActionPerformed

private void tTNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tTNoActionPerformed

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnExitActionPerformed

private void tPAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPAmtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPAmtActionPerformed

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

     String iId = tMemId1.getText();
    searchMem(iId);       
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnSearchActionPerformed

private void tMemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMemNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tMemNameActionPerformed

private void tMemId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMemId1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tMemId1ActionPerformed

private void btnSearchTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTActionPerformed
searchTrtm();
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnSearchTActionPerformed

private void tTForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTForActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tTForActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
  SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       Date date = new Date();
       today.setText("Date: "+dateFormat.format(date));
       search();// TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tMemId1;
    private javax.swing.JTextField tMemName;
    private javax.swing.JTextField tPAmt;
    private javax.swing.JTextField tPayNo;
    private javax.swing.JTextField tTFor;
    private javax.swing.JTextField tTNo;
    private javax.swing.JLabel today;
    // End of variables declaration//GEN-END:variables
}
