/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Treatment.java
 *
 * Created on May 5, 2015, 9:10:13 PM
 */
package gym;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author ManoJ
 */
public class Treatment extends javax.swing.JInternalFrame {

    /** Creates new form Treatment */
    public Treatment() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tPayNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tPAmt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tPAmt2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        phySch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        phyName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        memSch = new javax.swing.JButton();
        memName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tTFor = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setClosable(true);
        setTitle("Treatment ");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tPayNo.setEditable(false);
        tPayNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPayNoActionPerformed(evt);
            }
        });

        jLabel1.setText("Treatment No :");

        tPAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPAmtActionPerformed(evt);
            }
        });

        jLabel8.setText("Physiotherapist ID :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel2.setText("Treatment");

        tPAmt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPAmt2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Member No :");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });

        phySch.setText("Search");
        phySch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phySchActionPerformed(evt);
            }
        });

        jLabel11.setText("Physiotherapist Name :");

        phyName.setEditable(false);
        phyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phyNameActionPerformed(evt);
            }
        });

        memSch.setText("Search");
        memSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memSchActionPerformed(evt);
            }
        });

        memName.setEditable(false);
        memName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memNameActionPerformed(evt);
            }
        });

        jLabel13.setText("Member Name :");

        jLabel14.setText("Treatment For :");

        tTFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(tPayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phyName, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(tPAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phySch, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnAdd)
                .addGap(71, 71, 71)
                .addComponent(btnClr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tTFor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tPAmt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(memSch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(memName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(tPayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phySch)
                    .addComponent(tPAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPAmt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memSch)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tTFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnExit)
                    .addComponent(btnClr))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tPayNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPayNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPayNoActionPerformed

private void tPAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPAmtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPAmtActionPerformed

private void tPAmt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPAmt2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tPAmt2ActionPerformed

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
   this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnExitActionPerformed





 Connection con;
Statement st;
String i;
String a,b,c,d,e;
String a1,a2,a3,a4;
	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception exc){JOptionPane.showMessageDialog(null,exc);}
	}
    	void search()
	{	set();

            try
		{
		ResultSet rs=st.executeQuery("select * from  ProvideTrtmntT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d= rs.getString(5);
                                        
                }
		}catch(Exception hjhk){JOptionPane.showMessageDialog(null,hjhk);}
            
            Integer x = Integer.valueOf(i);         
            x=x+1;
            i = Integer.toString(x);
            tPayNo.setText(i); 
	}
           
            
private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
               
                if (tPAmt.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Physiotherapist Not Entered.");
                return;
                }

                           if (tPAmt2.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Member No Not Entered.");
                return;
                }
                                        if (tTFor.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Treatment Not Entered.");
                return;
                }

    try{       
               PreparedStatement pstmt = null;
                String query = "insert into ProvideTrtmntT(trtNo,phpstNo,memID,trtFor) values(?,?,?,?)";

     pstmt = con.prepareStatement(query); 
      pstmt.setString(1, i); 
      pstmt.setString(2,tPAmt.getText() );  
      pstmt.setString(3,tPAmt2.getText()); 
       pstmt.setString(4,tTFor.getText()); 

      pstmt.executeUpdate(); 
     
     JOptionPane.showMessageDialog(null,"Treatment Added..!");
                con.close();
		}catch(Exception e3){
                JOptionPane.showMessageDialog(null,e3);}
}//GEN-LAST:event_btnAddActionPerformed

           void search1(String z)
                {String b1,b2,b3;	
                    set();
             try
		{
		ResultSet rs=st.executeQuery("select * from  PhysiotherapistT");
		while(rs.next())
		{   
			b1=rs.getString(1);
			b2=rs.getString(2);
                        b3= rs.getString(3);
                        
                       if( b1.equals(z)){
                        phyName.setText(b2);                                                                        
                      }                               
                }
		}catch(Exception ex){}
	}
    
 
              
             void search3(String z)
                {String b1,b2,b3,b4,b5,b6,b7,b8;	
                    set();
             try
		{
		ResultSet rs=st.executeQuery("select * from  MemberT");
		while(rs.next())
		{   
			b1=rs.getString(1);
			b2=rs.getString(2);
                        b3= rs.getString(3);
                        b4=rs.getString(4);
                        b5= rs.getString(5);
                        b6= rs.getString(6);
                        b7=rs.getString(7);
                        b8= rs.getString(8);
                        
                        if( b1.equals(z)){
                        memName.setText(b2);                                                                        
                      }                               
                }
		}catch(Exception ex){}
	}
            
private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
tPAmt.setText("");
tPAmt2.setText("");


    // TODO add your handling code here:
}//GEN-LAST:event_btnClrActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
search();// TODO add your handling code here:
}//GEN-LAST:event_formInternalFrameActivated

private void phySchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phySchActionPerformed
search1(tPAmt.getText());        
 
    
    // TODO add your handling code here:
}//GEN-LAST:event_phySchActionPerformed

private void phyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phyNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_phyNameActionPerformed

private void memNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_memNameActionPerformed

private void memSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memSchActionPerformed
search3(tPAmt2.getText());// TODO add your handling code here:
}//GEN-LAST:event_memSchActionPerformed

private void tTForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTForActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tTForActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField memName;
    private javax.swing.JButton memSch;
    private javax.swing.JTextField phyName;
    private javax.swing.JButton phySch;
    private javax.swing.JTextField tPAmt;
    private javax.swing.JTextField tPAmt2;
    private javax.swing.JTextField tPayNo;
    private javax.swing.JTextField tTFor;
    // End of variables declaration//GEN-END:variables
}
