/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdatePhysican.java
 *
 * Created on Apr 1, 2015, 6:04:08 PM
 */
package gym;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ManoJ
 */
public class UpdatePhysican extends javax.swing.JInternalFrame {

    /** Creates new form UpdatePhysican */
    public UpdatePhysican() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iGndr1 = new javax.swing.JTextField();
        iID1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnClr1 = new javax.swing.JButton();
        iAdd1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        iName1 = new javax.swing.JTextField();
        iMob1 = new javax.swing.JTextField();

        setBorder(new javax.swing.border.SoftBevelBorder(0));
        setClosable(true);
        setTitle("Update Physican");

        iID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iID1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Mobile No :");

        jLabel6.setText("Name :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel7.setText("Update Physican");

        jLabel10.setText("Gender :");

        jLabel8.setText("Physican ID :");

        btnExit1.setText("Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd1.setText("Update");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnClr1.setText("Clear");
        btnClr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClr1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Address :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(iID1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(iName1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)
                        .addComponent(iAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd1)
                                .addGap(39, 39, 39)
                                .addComponent(btnClr1)
                                .addGap(53, 53, 53)
                                .addComponent(btnExit1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(iMob1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(18, 18, 18)
                                    .addComponent(iGndr1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(iID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(iName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(iAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(iMob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iGndr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd1)
                        .addComponent(btnClr1))
                    .addComponent(btnExit1))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void iID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iID1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_iID1ActionPerformed

private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
// TODO add your handling code here:
    
    this.dispose();
}//GEN-LAST:event_btnExit1ActionPerformed

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

     String iId = iID1.getText();
    search(iId);    
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnSearchActionPerformed
Connection con;
Statement st;
String i;
String a,b,c,d,e,f;

	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception exc){JOptionPane.showMessageDialog(null,exc);}
	}
    	void search(String z)
	{	set();
            try
		{
		ResultSet rs=st.executeQuery("select * from  PhysicanT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                        d = rs.getString(5);
                        
                       if( i.equals(z)){
                        iName1.setText(a);
                        iAdd1.setText(b);               
                        iMob1.setText(c);
                        iGndr1.setText(d);                                                                                        
                      }                               
                }
		}catch(Exception ex){}
	}











private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
                
    if (iName1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Name Not Entered.");
                return;
                }
                if (iAdd1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Address Not Entered.");
                return;
                }
                if (iMob1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Mobile No Not Entered.");
                return;
                }                
                
                if (iGndr1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Gender Not Entered.");
                return;
                }
                String id = iID1.getText();
                String name = iName1.getText();
                String add = iAdd1.getText();               
                String mob = iMob1.getText();
                String gndr = iGndr1.getText();
                         
                            
                //System.out.print(dob);
                //System.out.println(dob);System.out.println(MemName);System.out.println(MemAdrs);System.out.println(MemWeight);
                //   System.out.println(MemEmail);System.out.println(MemGender);
    
    
    
    try{       PreparedStatement pstmt = null;
               String sql = "UPDATE PhysicanT SET phyName=?,phyAdd=?,phyMob=?,phyGndr=? WHERE phyId = ?";
               pstmt = con.prepareStatement(sql);
        
                  
                  pstmt.setString(1,name ); 
                  pstmt.setString(2, add); 
                  pstmt.setString(3,mob); 
                  pstmt.setString(4,gndr ); 
                  pstmt.setString(5,id ); 
                  pstmt.executeUpdate(); 

               
        
     JOptionPane.showMessageDialog(null,"Physican "+name+" Updated..!");
                con.close();
		}catch(Exception x){
                JOptionPane.showMessageDialog(null,x);}
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnAdd1ActionPerformed

private void btnClr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClr1ActionPerformed
// TODO add your handling code here:
    iID1.setText("");
     iName1.setText("");
     iAdd1.setText("");               
     iMob1.setText("");
     iGndr1.setText("");
    
}//GEN-LAST:event_btnClr1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClr1;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField iAdd1;
    private javax.swing.JTextField iGndr1;
    private javax.swing.JTextField iID1;
    private javax.swing.JTextField iMob1;
    private javax.swing.JTextField iName1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
