/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpIns.java
 *
 * Created on Mar 29, 2015, 10:44:30 AM
 */
package gym;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ManoJ
 */
public class UpIns extends javax.swing.JInternalFrame {

    /** Creates new form UpIns */
    public UpIns() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iAdd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iName = new javax.swing.JTextField();
        iMob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iGndr = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        iID1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        iAdd1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        iName1 = new javax.swing.JTextField();
        iMob1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        btnClr1 = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        iID.setEditable(false);
        iID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Name :");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText("Add Instructor");

        jLabel2.setText("Instructor ID");

        jLabel4.setText("Address :");

        jLabel5.setText("Mobile No :");

        jLabel21.setText("Gender :");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClr.setText("Clear");

        btnExit.setText("Exit");

        setBorder(new javax.swing.border.SoftBevelBorder(0));
        setClosable(true);
        setTitle("Update Istructor");

        iID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iID1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Name :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel7.setText("Update Istructor");

        jLabel8.setText("Instructor ID");

        jLabel9.setText("Address :");

        jLabel10.setText("Mobile No :");

        btnAdd1.setText("Update");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnClr1.setText("Clear");
        btnClr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClr1ActionPerformed(evt);
            }
        });

        btnExit1.setText("Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(iID1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(iName1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)
                        .addComponent(iAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(iMob1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(btnAdd1)
                .addGap(33, 33, 33)
                .addComponent(btnClr1)
                .addGap(33, 33, 33)
                .addComponent(btnExit1)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(iID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(iName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(iAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(iMob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd1)
                        .addComponent(btnClr1))
                    .addComponent(btnExit1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void iIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_iIDActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                    
    
    
    
    
    
    
    
    
    
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnAddActionPerformed

private void iID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iID1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_iID1ActionPerformed

Connection con;
Statement st;
String i;
String a,b,c,d,e,f;

private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
                
    if (iName1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Name Not Entered.");
                return;
                }
                if (iAdd1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Address Not Entered.");
                return;
                }
                if (iMob1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Mobile No Not Entered.");
                return;
                }                

                String id = iID1.getText();
                String name = iName1.getText();
                String add = iAdd1.getText();               
                String mob = iMob1.getText();

                            
                //System.out.print(dob);
                //System.out.println(dob);System.out.println(MemName);System.out.println(MemAdrs);System.out.println(MemWeight);
                //   System.out.println(MemEmail);System.out.println(MemGender);
    
    
    
    try{       PreparedStatement pstmt = null;
               String sql = "UPDATE InstructorT SET insName=?,insAdd=?,insMob=? WHERE insID = ?";
               pstmt = con.prepareStatement(sql);
        
                  
                  pstmt.setString(1,name ); 
                  pstmt.setString(2, add); 
                  pstmt.setString(3,mob); 
                  pstmt.setString(4,id ); 
                  pstmt.executeUpdate(); 

               
        
     JOptionPane.showMessageDialog(null,"Istructor "+name+" Updated..!");
                con.close();
		}catch(Exception x){
                JOptionPane.showMessageDialog(null,x);}
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnAdd1ActionPerformed







	void set()
	{	try{
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		String ds=("jdbc:odbc:GYM");
		con=DriverManager.getConnection(ds,"","");
		st=con.createStatement();
		}catch(Exception exc){JOptionPane.showMessageDialog(null,exc);}
	}
    	void search(String z)
	{	set();
            try
		{
		ResultSet rs=st.executeQuery("select * from  InstructorT");
		while(rs.next())
		{       i=rs.getString(1);
			a=rs.getString(2);
                        b= rs.getString(3);
                        c= rs.getString(4);
                       
                        
                       if( i.equals(z)){
                        iName1.setText(a);
                        iAdd1.setText(b);               
                        iMob1.setText(c);
                                                                                                             
                      }                               
                }
		}catch(Exception ex){}
	}
private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

     String iId = iID1.getText();
    search(iId);    
    
    // TODO add your handling code here:
}//GEN-LAST:event_btnSearchActionPerformed

private void btnClr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClr1ActionPerformed
// TODO add your handling code here:
    iID1.setText("");
     iName1.setText("");
     iAdd1.setText("");               
     iMob1.setText("");
  
    
}//GEN-LAST:event_btnClr1ActionPerformed

private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
// TODO add your handling code here:
    
    this.dispose();
}//GEN-LAST:event_btnExit1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnClr1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField iAdd;
    private javax.swing.JTextField iAdd1;
    private javax.swing.JTextField iGndr;
    private javax.swing.JTextField iID;
    private javax.swing.JTextField iID1;
    private javax.swing.JTextField iMob;
    private javax.swing.JTextField iMob1;
    private javax.swing.JTextField iName;
    private javax.swing.JTextField iName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
